config/routes.rb
Rails.application.routes.draw do

  resources :items do
    member do
      get "vote"
    end
    collection do
      get "get_image_list"
      get "get_listings"
    end
  end

  resources :tags, only: [:index]
  match '/tags/:dehumanized_name', :via => :get, :to => 'tags#show'

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'items#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/views/elements/_navbar.html.haml
%nav.navbar.navbar-default{:role => "navigation"}
  -#Brand and toggle get grouped for better mobile display
  .navbar-header
    %button.navbar-toggle{"data-target" => "#navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar

    = link_to image_tag("totally_worth_it_logo_small_black.png", style: "height: 85%"), defined?(root_path) ? root_path : "#", class: "navbar-brand", style: "padding: 0; padding-top: 3px;"
  -# Collect the nav links, forms, and other content for toggling
  #navbar-collapse-1.collapse.navbar-collapse
    %ul.nav.navbar-nav
      %li.dropdown
        %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
          Categories
          %b.caret
        %ul.dropdown-menu
          - tags = Tag.order("taggings_count desc").limit(15).sort_by(&:name)
          - tags.each do |tag|
            - if tag.items.present?
              %li= link_to tag.name, "/tags/#{tag.dehumanized_name}"
    %ul.nav.navbar-nav.navbar-right
      - if defined?(Devise)
        - if user_signed_in?
          - if current_user.admin?
            %li= link_to "Add New Item", new_item_path
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              Account
              %b.caret
            %ul.dropdown-menu
              %li= link_to "Edit Account", edit_user_registration_path
              %li.divider
              %li= link_to "Sign Out", destroy_user_session_path, method: :delete
        - else
          %li= link_to "Login", new_user_session_path
          %li= link_to "Sign Up", new_user_registration_path